---

# ----------------------------------------------------------------------------
#  Add your Vagrant host as a dev repository
# ----------------------------------------------------------------------------
#yum_repos:
#    repo2:
#        name: 'Local'
#        baseurl: 'http://10.0.2.2:8080/repo'
#        descr: 'Local Dev Repo'

